# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Developer (roles/run.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 3. Change the values in the "env" block to match your values.

name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - main

jobs:
  db-migration:
    name: "Run DB Migration"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Set up Bun"
        uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"

      - name: "Install dependencies"
        run: |
          bun install

      - name: "Run migration"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_CERT: "${{ secrets.DB_CERT }}"
          NODE_ENV: production
        run: |
          bun db:push

  deploy:
    name: "Build and Deploy"
    needs: "db-migration"
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"

      - name: "Docker Auth"
        uses: "docker/login-action@v3"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.auth_token }}"
          registry: "${{ vars.REGION }}-docker.pkg.dev"

      - name: "Build and Push Container"
        id: "build-push"
        run: |
          DOCKER_TAG="${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
          echo "IMAGE_URL=${DOCKER_TAG}" >> $GITHUB_OUTPUT

      - name: "Deploy to Cloud Run"
        id: "deployment"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "${{ vars.SERVICE }}"
          region: "${{ vars.REGION }}"
          image: "${{ steps.build-push.outputs.IMAGE_URL }}"
          env_vars: |-
            DB_URL=${{ secrets.DB_URL }}
            DB_CERT="${{ secrets.DB_CERT }}"

      - name: "Show output"
        run: |
          echo "Cloud Run URL: ${{ steps.deployment.outputs.url }}"
          curl "${{ steps.deployment.outputs.url }}"
